apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: nexus
  labels:
    app: nexus
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 31081
    - name: docker
      port: 5000
      targetPort: 5000
      nodePort: 31500
  selector:
    app: nexus